name: 🚀 DEPLOYING WIE's WEBSITE!

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.18.3'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
          
      - name: 📂 deploy in ftp server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.smart-sfax.org
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: /wie-insat.ieee.tn/